   <h1>Connexion administrateur</h1>
   <form method="POST" action="admin-authentication">
        <label for="username">Nom d'utilisateur :</label>
        <input type="text" name="username" id="username" autocomplete="off">
        <br>
        <label for="password">Mot de passe :</label>
        <input type="password" name="password" id="password" autocomplete="off">

        <br>

        <input type="submit" value="Se connecter">
    </form>